# Generated by Django 5.2.3 on 2025-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                ("evaluation", models.JSONField(default=dict)),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
